# masterブランチがpushされた時にかつapiフォルダ以下のファイルが更新されている時のみワークフローを実行する
on:
  push:
    branches:
      - master    # 実行対象ブランチ
    paths:
      - 'api/*'   # api以下のファイル更新時のみワークフローが実行されるようにする

# 環境変数定義
env:
  NODE_VERSION: '8.x'   # aglioは8系が必要
  NAME: siwa32
  EMAIL: siwa32@gmail.com
  REPO: aglio-ghp-demo

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest    # ワークフローを実行するコンテナのOS
    steps:
    - uses: actions/checkout@v2   # masterブランチをチェックアウト

    # Nodeのバージョンを指定
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    # シェルでnpmコマンド実行
    # package.json に build コマンドを定義している
    # aglioによりbuildディレクトリにhtmlファイルが生成される
    - name: npm install, build
      run: |
        # Build project
        npm install
        npm run build --if-present
      shell: bash

    # git pushするためにgit設定
    - name: git config settings
      run: |
        git config user.name ${{ env.NAME }}
        git config user.email ${{ env.EMAIL }}
        git remote set-url origin https://${{ env.NAME }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.NAME }}/${{ env.REPO }}

    # build/*.htmlをdocs/にコピーしてcommit and push
    # doc/*は無視リストに入っているのでgit addには-fオプションを付加
    - name: commit and push
      run: |
        git checkout master
        git branch -a
        cp build/*.html docs/
        git add -f docs/*.html
        git commit -m "update api spec"
        git push origin master
      shell: bash
